### ISSUE TITLE
Exception thrown in extension is not handled

### ISSUE THREAD

**Issue by pawel-smuga** [reportportal/agent-java-junit5#108]
**Describe the bug**
I have a JUnit5 extensions which I register with `@ExtendWith` annotation. The extensions implements `BeforeEachCallback` and `BeforeAllCallback` interfaces. When I run the test class for which the extension is registered, and an exception is thrown in `beforeEach` or `beforeAll` methods of the extension, the exceptions are not handled properly (i.e. are not reported in RP).

**Steps to Reproduce**
Run test classes of the following code
```
import org.assertj.core.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;

public class ExampleTest {

    // ACTUAL RESULT (for all the test cases):
    // - the failure is not reported in RP
    // - the test class remains in "in progress" state in RP until launch is finished. Then it gets status "interrupted"
    // - exception is thrown in logs (retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request)
    public static class AssumptionCases {

        // EXPECTED: this should get reported as skipped (in "beforeAll" method)
        @ExtendWith(Extensions.FailedAssumptionBeforeAllExtension.class)
        public static class FailedAssumptionBeforeAllExtensionTest {

            @Test
            void assumptionFailedInBeforeAllExtensionTest() {
            }

        }

        // EXPECTED: this should get reported as skipped (in "beforeEach" method)
        @ExtendWith(Extensions.FailedAssumptionBeforeEachExtension.class)
        public static class FailedAssumptionBeforeEachExtensionTest {

            @Test
            void assumptionFailedInBeforeEachExtensionTest() {
            }

        }

        // EXPECTED: this should get reported as failed (in "beforeAll" method (?))
        @ExtendWith(Extensions.ExceptionThrownBeforeAllExtension.class)
        public static class ExceptionThrownBeforeAllExtensionTest {

            @Test
            void exceptionThrownInBeforeAllExtensionTest() {
            }

        }

        // EXPECTED: this should get reported as failed (in "beforeEach" method)
        @ExtendWith(Extensions.ExceptionThrownBeforeEachExtension.class)
        public static class ExceptionThrownBeforeEachExtensionTest {

            @Test
            void exceptionThrownInBeforeEachTest() {
            }

        }
    }

    public static class Extensions {

        public static class ExceptionThrownBeforeAllExtension implements BeforeAllCallback {

            @Override
            public void beforeAll(ExtensionContext context) throws Exception {
                throw new IllegalArgumentException("exception");
            }

        }

        public static class ExceptionThrownBeforeEachExtension implements BeforeEachCallback {

            @Override
            public void beforeEach(ExtensionContext context) throws Exception {
                throw new IllegalArgumentException("exception");
            }
        }

        public static class FailedAssumptionBeforeAllExtension implements BeforeAllCallback {

            @Override
            public void beforeAll(ExtensionContext context) throws Exception {
                Assumptions.assumeThat(true).isFalse();
                // or other supported assumption
            }

        }

        public static class FailedAssumptionBeforeEachExtension implements BeforeEachCallback {

            @Override
            public void beforeEach(ExtensionContext context) throws Exception {
                Assumptions.assumeThat(true).isFalse();
                // or other supported assumption
            }
        }

    }

}
```

**Expected behavior**
The exceptions thrown from within `beforeEach` or `beforeAll` methods of the extensions, are handled properly, i.e. presented in Report Portal as Failure or Skipped (respectively to the exception type) - the same way as an exception is handled when thrown from `@BeforeAll` or `@BeforeEach` annotated methods.

**Actual behavior**
- the failure is not reported in RP
- the test class remains in "in progress" state in RP until launch is finished. Then it gets status "interrupted"
- exception is thrown in logs (retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request)
```ERROR [   rp-io-8]                    Launch:46  : [31] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:?]
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:?]
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12267) ~[rxjava-2.2.10.jar:?]
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12267) ~[rxjava-2.2.10.jar:?]
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.2.10.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.10.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
ERROR [   rp-io-8]         SubscriptionUtils:98  : [31] ReportPortal Finish test item execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:?]
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:?]
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12267) ~[rxjava-2.2.10.jar:?]
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12267) ~[rxjava-2.2.10.jar:?]
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.2.10.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) ~[rxjava-2.2.10.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) ~[rxjava-2.2.10.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

**Dependency versions**
client-java => 5.1.11
agent-java-junit5 => 5.1.5

**Additional context**
none

**Comment by HardNorth** [comment]
@pawel-smuga It's not possible and won't be possible any time soon.
