### ISSUE TITLE
java.lang.ClassNotFoundException: when using junit-platform-console-standalone jar

### ISSUE THREAD

**Issue by mabbas007** [reportportal/agent-java-junit5#118]
**Describe the bug**
When running tests using `junit-platform-console-standalone-1.10.1.jar` from a fat jar containing all the tests and dependencies 
everything seems to be reported as expected to ReportPortal but it will throw `java.lang.ClassNotFoundException` at the end causing the test not to be finished on ReportPortal

**Steps to Reproduce**
1. Generate a fat jar using Shadow jar containing all your tests, app-tests.jar
2. Run tests using junit console launcher: `java --add-opens=java.base/java.lang=ALL-UNNAMED -jar junit-platform-console-standalone-1.10.1.jar --disable-ansi-colors execute -cp app-tests.jar --select-package com.mycompany.uat.tests`

**Expected behavior**
For the tests to finish executing without an exception

**Actual behavior**
The following exception is thrown after successfully running tests

```
╷
├─ JUnit Jupiter ✔
│  ├─ LoginTest ✔
│  │  └─ testLogin() 96954 ms ✔
│  └─ SignInOptionsTest ✔
│     └─ testAllSignInOptionsAreAvailable() 12234 ms ✔
├─ JUnit Vintage ✔
└─ JUnit Platform Suite ✔

Test run finished after 109630 ms
[         5 containers found      ]
[         0 containers skipped    ]
[         5 containers started    ]
[         0 containers aborted    ]
[         5 containers successful ]
[         0 containers failed     ]
[         2 tests found           ]
[         0 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         0 tests failed          ]

Exception in thread "Thread-2" java.lang.NoClassDefFoundError: com/epam/reportportal/service/launch/SecondaryLaunchFinishCondition
        at com.epam.reportportal.service.launch.PrimaryLaunch.finish(PrimaryLaunch.java:54)
        at com.epam.reportportal.junit5.ReportPortalExtension.finish(ReportPortalExtension.java:112)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at com.epam.reportportal.junit5.ReportPortalExtension.lambda$getShutdownHook$2(ReportPortalExtension.java:116)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.epam.reportportal.service.launch.SecondaryLaunchFinishCondition
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 5 more

```

**Dependency versions**
```
// Use the Kotlin JUnit 5 integration.
    implementation("org.jetbrains.kotlin:kotlin-test-junit5:1.8.10")
    implementation("com.epam.reportportal:logger-java-log4j:5.1.8")
    implementation("org.apache.logging.log4j:log4j-api:2.22.0")
    implementation("org.apache.logging.log4j:log4j-core:2.22.0")
    implementation("com.epam.reportportal:agent-java-junit5:5.1.11")
```

**Comment by HardNorth** [comment]
@mabbas007 There is no issue with our code, it's all about how you build your fat jar, take a look at this example: https://github.com/bonigarcia/webdrivermanager/issues/819
