### ISSUE TITLE
Unable to run Android instrumentation tests on JUnit5. No virtual method getAnnotatedParameterTypes()

### ISSUE THREAD

**Issue by Nik-Kudrin** [reportportal/agent-java-junit5#66]
Hello, guys.

We have a problem running test on JUnit5 on Android.
agent-java-junit5:5.0.0
logger-java-logback:5.0.2

Run commands (you may just run a command from terminal)
 ```
adb shell am instrument -w -r -e runnerBuilder de.mannodermaus.junit5.AndroidJUnit5Builder -e newRunListenerMode true   -e debug false -e class 'ru.x.qa.android.uitest.test.AndroidDummyTest#someAndroidTest' x.qa.android.test/androidx.test.runner.AndroidJUnitRunner
```

Run  log
```
Testing started at 12:08 ...

08/07 12:08:53: Launching 'someAndroidTest()' on Pixel 2 API 30.
Running tests

$ adb shell am instrument -w -r -e runnerBuilder de.mannodermaus.junit5.AndroidJUnit5Builder -e newRunListenerMode true   -e debug false -e class 'ru.x.qa.android.uitest.test.AndroidDummyTest#someAndroidTest' x.qa.android.test/androidx.test.runner.AndroidJUnitRunner
Connected to process 28012 on device 'Pixel_2_API_30 [emulator-5554]'.

Started running tests


java.util.ServiceConfigurationError: org.junit.jupiter.api.extension.Extension: Provider com.epam.reportportal.junit5.ReportPortalExtension could not be instantiated
at java.util.ServiceLoader.fail(ServiceLoader.java:233)
at java.util.ServiceLoader.access$100(ServiceLoader.java:183)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:392)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:416)
at java.util.ServiceLoader$1.next(ServiceLoader.java:494)
at java.lang.Iterable.forEach(Iterable.java:74)
at org.junit.jupiter.engine.extension.MutableExtensionRegistry.registerAutoDetectedExtensions(MutableExtensionRegistry.java:99)
at org.junit.jupiter.engine.extension.MutableExtensionRegistry.createRegistryWithDefaultExtensions(MutableExtensionRegistry.java:83)
at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.prepare(JupiterEngineDescriptor.java:51)
at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.prepare(JupiterEngineDescriptor.java:29)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1$NodeTestTask(NodeTestTask.java:107)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$hn7IbVcEIq2SM-8pZLhWXU13_ik.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5$DefaultLauncher(DefaultLauncher.java:211)
at org.junit.platform.launcher.core.-$$Lambda$DefaultLauncher$18HGgHXWMNsTa7ft-07mpf_m5XE.accept(Unknown Source:10)
at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:141)
at de.mannodermaus.junit5.AndroidJUnit5.run(AndroidJUnit5.java:111)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: java.lang.NoSuchMethodError: No virtual method getAnnotatedParameterTypes()[Ljava/lang/reflect/AnnotatedType; in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /apex/com.android.art/javalib/core-oj.jar)
at rp.com.google.common.reflect.Invokable$MethodInvokable.getAnnotatedParameterTypes(Invokable.java:223)
at rp.com.google.common.reflect.Invokable.getParameters(Invokable.java:120)
at com.epam.reportportal.restendpoint.http.proxy.RestMethodInfo.parseMethod(RestMethodInfo.java:128)
at com.epam.reportportal.restendpoint.http.proxy.RestMethodInfo.<init>(RestMethodInfo.java:105)
at com.epam.reportportal.restendpoint.http.proxy.RestMethodInfo.mapMethods(RestMethodInfo.java:66)
at com.epam.reportportal.restendpoint.http.proxy.RestEndpointInvocationHandler.<init>(RestEndpointInvocationHandler.java:33)
at com.epam.reportportal.restendpoint.http.RestEndpoints.forInterface(RestEndpoints.java:92)
at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:436)
at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:401)
at com.epam.reportportal.junit5.ReportPortalExtension.<clinit>(ReportPortalExtension.java:71)
at java.lang.Class.newInstance(Native Method)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:388)
... 36 more

Tests ran to completion.
```

Full log from Logcat
```
2020-08-07 12:08:53.192 28012-28012/? I/x.qa.android: Not late-enabling -Xcheck:jni (already on)
2020-08-07 12:08:53.203 28012-28012/x.qa.android I/x.qa.android: Unquickening 12 vdex files!
2020-08-07 12:08:53.203 28012-28012/x.qa.android W/x.qa.android: Unexpected CPU variant for X86 using defaults: x86
2020-08-07 12:08:53.224 28012-28012/x.qa.android D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-08-07 12:08:53.226 28012-28012/x.qa.android I/x.qa.android: The ClassLoaderContext is a special shared library.
2020-08-07 12:08:53.227 28012-28012/x.qa.android I/chatty: uid=10178(x.qa.android) identical 1 line
2020-08-07 12:08:53.228 28012-28012/x.qa.android I/x.qa.android: The ClassLoaderContext is a special shared library.
2020-08-07 12:08:53.515 28012-28012/x.qa.android D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-08-07 12:08:53.515 28012-28012/x.qa.android D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-08-07 12:08:53.516 28012-28012/x.qa.android I/x.qa.android: The ClassLoaderContext is a special shared library.
2020-08-07 12:08:53.517 28012-28012/x.qa.android D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-08-07 12:08:53.517 28012-28012/x.qa.android D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-08-07 12:08:53.517 28012-28012/x.qa.android I/x.qa.android: The ClassLoaderContext is a special shared library.
2020-08-07 12:08:53.519 28012-28012/x.qa.android I/chatty: uid=10178(x.qa.android) identical 2 lines
2020-08-07 12:08:53.520 28012-28012/x.qa.android I/x.qa.android: The ClassLoaderContext is a special shared library.
2020-08-07 12:08:53.817 28012-28012/x.qa.android W/x.qa.android: Accessing hidden method Landroid/app/Instrumentation;->execStartActivity(Landroid/content/Context;Landroid/os/IBinder;Landroid/os/IBinder;Landroid/app/Activity;Landroid/content/Intent;ILandroid/os/Bundle;)Landroid/app/Instrumentation$ActivityResult; (greylist, linking, allowed)
2020-08-07 12:08:53.817 28012-28012/x.qa.android W/x.qa.android: Accessing hidden method Landroid/app/Instrumentation;->execStartActivity(Landroid/content/Context;Landroid/os/IBinder;Landroid/os/IBinder;Ljava/lang/String;Landroid/content/Intent;ILandroid/os/Bundle;)Landroid/app/Instrumentation$ActivityResult; (greylist, linking, allowed)
2020-08-07 12:08:53.820 28012-28012/x.qa.android D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-08-07 12:08:53.820 28012-28012/x.qa.android D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-08-07 12:08:53.820 28012-28012/x.qa.android I/MonitoringInstr: Instrumentation started!
2020-08-07 12:08:53.833 28012-28012/x.qa.android I/MonitoringInstr: No JSBridge.
2020-08-07 12:08:53.838 28012-28034/x.qa.android I/UsageTrackerFacilitator: Usage tracking enabled
2020-08-07 12:08:53.882 28012-28034/x.qa.android I/ConfigurationParameters: Loading JUnit Platform configuration parameters from classpath resource [jar:file:/data/app/~~KJ7qJ2oDAaCtADfk8GlzuQ==/x.qa.android-TMmePuYiOWt4EM7zv3Ah6Q==/base.apk!/junit-platform.properties].
2020-08-07 12:08:53.931 28012-28034/x.qa.android W/x.qa.android: Accessing hidden field Llibcore/io/Libcore;->os:Llibcore/io/Os; (greylist, reflection, allowed)
2020-08-07 12:08:53.931 28012-28034/x.qa.android W/x.qa.android: Accessing hidden method Llibcore/io/ForwardingOs;->setenv(Ljava/lang/String;Ljava/lang/String;Z)V (greylist, reflection, allowed)
2020-08-07 12:08:53.936 28012-28034/x.qa.android D/TestExecutor: Adding listener androidx.test.internal.runner.listener.LogRunListener
2020-08-07 12:08:53.936 28012-28034/x.qa.android D/TestExecutor: Adding listener androidx.test.internal.runner.listener.InstrumentationResultPrinter
2020-08-07 12:08:53.936 28012-28034/x.qa.android D/TestExecutor: Adding listener androidx.test.internal.runner.listener.ActivityFinisherRunListener
2020-08-07 12:08:53.936 28012-28034/x.qa.android I/TestRunner: run started: 1 tests
2020-08-07 12:08:54.073 28012-28034/x.qa.android E/TestRunner: failed: JUnit Jupiter
2020-08-07 12:08:54.073 28012-28034/x.qa.android E/TestRunner: ----- begin exception -----
2020-08-07 12:08:54.074 28012-28034/x.qa.android E/TestRunner: java.util.ServiceConfigurationError: org.junit.jupiter.api.extension.Extension: Provider com.epam.reportportal.junit5.ReportPortalExtension could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:233)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:183)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:392)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:416)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:494)
        at java.lang.Iterable.forEach(Iterable.java:74)
        at org.junit.jupiter.engine.extension.MutableExtensionRegistry.registerAutoDetectedExtensions(MutableExtensionRegistry.java:99)
        at org.junit.jupiter.engine.extension.MutableExtensionRegistry.createRegistryWithDefaultExtensions(MutableExtensionRegistry.java:83)
        at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.prepare(JupiterEngineDescriptor.java:51)
        at org.junit.jupiter.engine.descriptor.JupiterEngineDescriptor.prepare(JupiterEngineDescriptor.java:29)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1$NodeTestTask(NodeTestTask.java:107)
        at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$hn7IbVcEIq2SM-8pZLhWXU13_ik.execute(Unknown Source:2)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5$DefaultLauncher(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.-$$Lambda$DefaultLauncher$18HGgHXWMNsTa7ft-07mpf_m5XE.accept(Unknown Source:10)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:141)
        at de.mannodermaus.junit5.AndroidJUnit5.run(AndroidJUnit5.java:111)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
     Caused by: java.lang.NoSuchMethodError: No virtual method getAnnotatedParameterTypes()[Ljava/lang/reflect/AnnotatedType; in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /apex/com.android.art/javalib/core-oj.jar)
        at rp.com.google.common.reflect.Invokable$MethodInvokable.getAnnotatedParameterTypes(Invokable.java:223)
        at rp.com.google.common.reflect.Invokable.getParameters(Invokable.java:120)
2020-08-07 12:08:54.074 28012-28034/x.qa.android E/TestRunner:     at com.epam.reportportal.restendpoint.http.proxy.RestMethodInfo.parseMethod(RestMethodInfo.java:128)
        at com.epam.reportportal.restendpoint.http.proxy.RestMethodInfo.<init>(RestMethodInfo.java:105)
        at com.epam.reportportal.restendpoint.http.proxy.RestMethodInfo.mapMethods(RestMethodInfo.java:66)
        at com.epam.reportportal.restendpoint.http.proxy.RestEndpointInvocationHandler.<init>(RestEndpointInvocationHandler.java:33)
        at com.epam.reportportal.restendpoint.http.RestEndpoints.forInterface(RestEndpoints.java:92)
        at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:436)
        at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:401)
        at com.epam.reportportal.junit5.ReportPortalExtension.<clinit>(ReportPortalExtension.java:71)
        at java.lang.Class.newInstance(Native Method)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:388)
        	... 36 more
2020-08-07 12:08:54.074 28012-28034/x.qa.android E/TestRunner: ----- end exception -----
2020-08-07 12:08:54.077 28012-28034/x.qa.android I/TestRunner: run finished: 0 tests, 1 failed, 0 ignored
2020-08-07 12:08:54.249 28012-28034/? I/MonitoringInstr: waitForActivitiesToComplete() took: 0ms
```

build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'de.mannodermaus.android-junit5'

android {
	compileSdkVersion 29
	buildToolsVersion "29.0.3"

	defaultConfig {
		applicationId "x.qa.android"
		minSdkVersion 26
		targetSdkVersion 29
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		testInstrumentationRunnerArguments(
				'newRunListenerMode': 'true',
				'runnerBuilder': 'de.mannodermaus.junit5.AndroidJUnit5Builder'
		)
	}

	lintOptions {
		lintConfig file("lint.xml")
	}

	buildTypes {
		debug {
			useProguard false
			minifyEnabled false
			shrinkResources false
			manifestPlaceholders = [
					excludeSystemAlertWindowPermission: "false" // Fix for stripping unwanted permissions - https://github.com/facebook/react-native/issues/5886#issuecomment-224397883
			]
		}
	}

	packagingOptions {
		exclude 'META-INF/LICENSE*'
		exclude 'META-INF/NOTICE*'
		exclude 'META-INF/DEPENDENCIES*'
		exclude 'logback.xml'
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

	kotlinOptions {
		jvmTarget = JavaVersion.VERSION_1_8.toString()
	}

	productFlavors {
	}

	sourceSets {
		androidTest.java.srcDirs += ['src/androidTest/kotlin']
	}

}


dependencies {
	androidTestImplementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${rootProject.kotlinVersion}"
	androidTestImplementation 'com.google.guava:guava:29.0-android'
	androidTestImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.7'

	androidTestImplementation("com.epam.reportportal:agent-java-junit5:5.0.0") {
		// Because of:
		// java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class org.aspectj.internal.lang.annotation.ajcDeclareAnnotation
		// found in modules aspectjrt-1.9.2.jar (org.aspectj:aspectjrt:1.9.2) and aspectjweaver-1.9.2.jar (org.aspectj:aspectjweaver:1.9.2)
		exclude module: 'aspectjrt'
	}
	androidTestImplementation("com.epam.reportportal:logger-java-logback:5.0.2") {
		exclude module: 'aspectjrt'
	}
	androidTestImplementation 'org.slf4j:slf4j-api:1.7.30'
	androidTestImplementation 'ch.qos.logback:logback-classic:1.2.3'

	androidTestImplementation "androidx.test:core:1.3.0-beta02"
	androidTestImplementation "androidx.test.ext:junit:1.1.2-beta02"
	androidTestImplementation "androidx.test:runner:1.3.0-beta01"

	androidTestImplementation "org.junit.jupiter:junit-jupiter-api:5.6.0"
	androidTestRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.6.0"
	androidTestImplementation "org.junit.jupiter:junit-jupiter-params:5.6.0"

	androidTestImplementation "de.mannodermaus.junit5:android-test-core:1.2.0"
	androidTestRuntimeOnly "de.mannodermaus.junit5:android-test-runner:1.2.0"

	androidTestImplementation "androidx.test.uiautomator:uiautomator:2.2.0"
}

```

I attached simple project for test purpose
[UiTests.zip](https://github.com/reportportal/agent-java-junit5/files/5040458/UiTests.zip)

**Comment by Nik-Kudrin** [comment]
We were able to run tests on junit5 v4.x.x. But unfortunately, it didn't work well with Reportportal v5.0.0 (E.g.: test hanged in report portal as unfinished)
agent-java-junit5:4.0.3
logger-java-logback:4.0.5

build.gradle for that configuration

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'de.mannodermaus.android-junit5'

android {
	compileSdkVersion 29
	buildToolsVersion "29.0.3"

	defaultConfig {
		applicationId "x.x.x"
		minSdkVersion 26
		targetSdkVersion 29
		testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
		testInstrumentationRunnerArguments(
				'newRunListenerMode': 'true',
				'runnerBuilder': 'de.mannodermaus.junit5.AndroidJUnit5Builder'
		)
	}

	lintOptions {
		lintConfig file("lint.xml")
	}

	buildTypes {
		debug {
			useProguard false
			minifyEnabled false
			shrinkResources false
			manifestPlaceholders = [
					excludeSystemAlertWindowPermission: "false" // Fix for stripping unwanted permissions - https://github.com/facebook/react-native/issues/5886#issuecomment-224397883
			]
		}
	}

	packagingOptions {
		exclude 'META-INF/LICENSE*'
		exclude 'META-INF/NOTICE*'
		exclude 'META-INF/DEPENDENCIES*'
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_8
		targetCompatibility JavaVersion.VERSION_1_8
	}

	kotlinOptions {
		jvmTarget = JavaVersion.VERSION_1_8.toString()
	}

	productFlavors {
	}

	sourceSets {
		androidTest.java.srcDirs += ['src/androidTest/kotlin']
	}
}


dependencies {	
	androidTestImplementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${rootProject.kotlinVersion}"
	androidTestImplementation 'com.google.guava:guava:29.0-android'
	androidTestImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.7'

	// Report portal dependencies
	androidTestImplementation("com.epam.reportportal:agent-java-junit5:4.0.3")
	androidTestImplementation("com.epam.reportportal:logger-java-logback:4.0.5")
	androidTestImplementation 'org.slf4j:slf4j-api:1.7.30'
	androidTestImplementation 'ch.qos.logback:logback-classic:1.2.3'

	// Because of:
	// io.mockk.MockKException: Failed to load plugin. io.mockk.proxy.android.AndroidMockKAgentFactory
	// Android instrumented test is running, include 'io.mockk:mockk-android' dependency instead 'io.mockk:mockk'
	androidTestImplementation 'io.mockk:mockk-android:1.10.0'

	androidTestImplementation "androidx.test:core:1.3.0-beta02"
	androidTestImplementation "androidx.test.ext:junit:1.1.2-beta02"
	androidTestImplementation "androidx.test:runner:1.3.0-beta01"

	androidTestImplementation "org.junit.jupiter:junit-jupiter-api:5.6.0"
	androidTestRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.6.0"
	androidTestImplementation "org.junit.jupiter:junit-jupiter-params:5.6.0"

	androidTestImplementation "de.mannodermaus.junit5:android-test-core:1.2.0"
	androidTestRuntimeOnly "de.mannodermaus.junit5:android-test-runner:1.2.0"

	androidTestImplementation "androidx.test.uiautomator:uiautomator:2.2.0"
}
```

**Comment by HardNorth** [comment]
The issue is not related to the agent.

`com.epam.reportportal.junit5.ReportPortalExtension.<clinit>(ReportPortalExtension.java:71)`
That means it's related to the initialization process [line 71](https://github.com/reportportal/agent-java-junit5/blob/develop/src/main/java/com/epam/reportportal/junit5/ReportPortalExtension.java#L71), which is ReportPortal client creation. It goes further to our Rest client and fails on a simple line: `(parameter.isAnnotationPresent(Multipart.class))`

So, I believe this is a strong evidence that it's not related to our code at all.

Logically I can link such behavior changes with our migration on Java 8 in all client code. Well, we couldn't stay on Java 6 due to many reasons. And the first of them is the absence of basic interfaces inside Java 6.

There might be a solution to use Retrofit instead of our Rest client as they claim they are "A type-safe HTTP client for Android and Java", but this will not appear in any 5th version of the client. Even 6th is under question here.
